apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-app-config
data:
  main.py: |
    from fastapi import FastAPI, Request

    app = FastAPI()

    @app.post("/hello")
    async def hello(request: Request):
        headers = request.headers
        body = await request.body()
        return {
            "headers": dict(headers),
            "body": body.decode("utf-8")
        }
