apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish-pg-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: varnish-pg-backend
  template:
    metadata:
      labels:
        app: varnish-pg-backend
    spec:
      containers:
      - name: varnish-pg-backend
        image: alifyasa/varnish-pg-backend:latest
        ports:
        - containerPort: 8000
