varnish-cache:
  server:
    vclConfig: |
      vcl 4.1;

      backend default {
        .host = "simple-server-service";
        .port = "80";
      }

      sub vcl_backend_fetch {
        set bereq.http.Host = "www.example.com";
        set bereq.http.X-Custom-Header = "MyValue";
      }
