varnish-cache:
  server:
    vclConfig: |
      vcl 4.1;
      include "devicedetect.vcl";

      backend default {
        .host = "varnish-pg-service";
        .port = "80";
      }

      sub vcl_recv {
        call devicedetect;
      }
      
      sub vcl_backend_response {
        set beresp.ttl = 5m;
        if (bereq.http.X-UA-Device) {
          if (!beresp.http.Vary) { # no Vary at all
            set beresp.http.Vary = "X-UA-Device";
          } elsif (beresp.http.Vary !~ "X-UA-Device") { # add to existing Vary
            set beresp.http.Vary = beresp.http.Vary + ", X-UA-Device";
          }
        }
        # comment this out if you don't want the client to know your classification
        set beresp.http.X-UA-Device = bereq.http.X-UA-Device;
      }

      sub vcl_deliver {
        if ((req.http.X-UA-Device) && (resp.http.Vary)) {
          set resp.http.Vary = regsub(resp.http.Vary, "X-UA-Device", "User-Agent");
        }
      }
