varnish-cache:
  server:
    vclConfig: |
      vcl 4.1;
      include "devicedetect.vcl";

      backend default {
        .host = "simple-server-service";
        .port = "80";
      }

      sub vcl_backend_fetch {
        set bereq.http.Host = "www.example.com";  # Set Host header for backend requests
        set bereq.http.X-Custom-Header = "CustomValue";  # Add custom header to backend request
      }

      sub vcl_recv {
        call devicedetect;
      }

      sub vcl_hash {
        hash_data(req.url);  # Create cache key based on request URL
        hash_data(req.http.User-Agent);  # Hash 'User-Agent' header
        hash_data(req.http.X-Forwarded-For);  # Include forwarded IP in cache key
        hash_data(client.ip);  # Include client's IP in cache key
      }
      
      sub vcl_backend_response {
        if (bereq.http.X-UA-Device) {
          if (!beresp.http.Vary) { # no Vary at all
            set beresp.http.Vary = "X-UA-Device";
          } elsif (beresp.http.Vary !~ "X-UA-Device") { # add to existing Vary
            set beresp.http.Vary = beresp.http.Vary + ", X-UA-Device";
          }
        }
        # comment this out if you don't want the client to know your classification
        set beresp.http.X-UA-Device = bereq.http.X-UA-Device;
      }

      sub vcl_deliver {
        if ((req.http.X-UA-Device) && (resp.http.Vary)) {
          set resp.http.Vary = regsub(resp.http.Vary, "X-UA-Device", "User-Agent");
        }
      }
